variables:
  DOCKER_REPO: registry.gitlab.com
  MAIN_IMAGE_NAME: shophobe/shophobe-vendor/image

stages:
  - build

build:
  image: fahim74/nodejs-yarn-docker
  stage: build
  services:
    - docker:dind
  script:
    - yarn
    - yarn build:dev
    - docker login -u thebdcoder -p uXhyx3zANhFABaW9mzcD $DOCKER_REPO
    - docker build -t $DOCKER_REPO/$MAIN_IMAGE_NAME:latest .
    - docker build -t $DOCKER_REPO/$MAIN_IMAGE_NAME:$CI_COMMIT_REF_NAME .
    - docker push $DOCKER_REPO/$MAIN_IMAGE_NAME:latest
    - docker push $DOCKER_REPO/$MAIN_IMAGE_NAME:$CI_COMMIT_REF_NAME
